.PHONY: parse_trans parse_trans_examples clean

all: parse_trans parse_trans_examples

parse_trans:
	make -C parse_trans

parse_trans_examples:
	make -C parse_trans_examples

clean:
	make -C parse_trans clean
	make -C parse_trans_examples clean
