.PHONY: all deps parse_trans parse_trans_examples clean

all: parse_trans parse_trans_examples

deps:
	(cd parse_trans; ./rebar get-deps)

parse_trans:
	make -C parse_trans

parse_trans_examples:
	make -C parse_trans_examples

clean:
	make -C parse_trans clean
	make -C parse_trans_examples clean
